services:
  next:
    container_name: next-dev
    image: node:20
    working_dir: /app
    volumes:
      - ./web:/app
    ports:
      - "3000:3000"
    # 開発環境のみのコマンド
    command: sh -c "npm install && npm run dev"

  nginx:
    image: nginx:1.21.1
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./web/out:/usr/share/nginx/html
      - ./api:/var/www/
    depends_on:
      - php

  php:
    build: ./docker/php
    user: "1000:1000"
    volumes:
      - ./api:/var/www/
    ports:
      - "9000:9000"

  mysql:
    image: mysql:8.0.26
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_pass
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=laravel_user
      - PMA_PASSWORD=laravel_pass
    depends_on:
      - mysql
    ports:
      - 8080:80
